language: erlang

branches:
  only:
    - "master"

otp_release:
  - 21.0
  - 19.3
  - 18.3
  - 17.0 # 17.5 concrete PLT has some issues; dig into them

addons:
  postgresql: 9.6

install: true

script: "make get-rebar all"
